### ISSUE TITLE
remove will crash if presented with a nonexistent package

### ISSUE THREAD

**Issue by ItsMajestiX** [ItsMajestiX/ServerModManager#1]
the title explains most of it

reproduction steps:
1. `scpman remove aaa`
2. Will crash with stack dump: 
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ServerModManager.Remover.remove(Package package, Validator val) in D:\Users\Majes\source\repos\ServerModManager\ServerModManager\Commands\Remover.cs:line 35
   at ServerModManager.Remover.removePackages(Validator val, PackageOverview overview) in D:\Users\Majes\source\repos\ServerModManager\ServerModManager\Commands\Remover.cs:line 42
   at ServerModManager.Program.Main(String[] args) in D:\Users\Majes\source\repos\ServerModManager\ServerModManager\Program.cs:line 30`

**Comment by ItsMajestiX** [comment]
this error also happens with `update` too

**Comment by ItsMajestiX** [comment]
Just tested and confirmed fixed with new commit. Closed.
